### ISSUE TITLE
Add OurAirport Support

### ISSUE THREAD

**Issue by nick-zrymiak** [sfu-db/DataConnectorConfigs#107]
Website Description
OurAirport is a service that gives information on airports in certain regions and nearest airports.

Reason(s) to Support the Website
Developers making travel applications can use this website for accessing airport data based on certain properties.

Endpoints
- This API supports 6 endpoints but one gives 400 error and another endpoint serves the same purpose as one of the endpoints in IPLegit. A third requires one of two parameters and this API uses the template URL functionality which currently doesn't support this case.
https://ourairport-data-search.p.rapidapi.com/airport
https://ourairport-data-search.p.rapidapi.com/country
https://ourairport-data-search.p.rapidapi.com/region

Questions
1. What is the country given GeoNames ID?
2. What are region names of a range of ID numbers?
3. What are all countries in Asia?

**Comment by Yizhou150** [comment]
Sounds good! It would be better if you could create some questions like "what are the airports in a country?", that returns a list of records. Good job! :D

**Comment by nick-zrymiak** [comment]
> Sounds good! It would be better if you could create some questions like "what are the airports in a country?", that returns a list of records. Good job! :D

Sure! I'll use that question.

**Comment by nick-zrymiak** [comment]
> Sounds good! It would be better if you could create some questions like "what are the airports in a country?", that returns a list of records. Good job! :D

Thanks Jess! This question can't be answered with the endpoints DataPrep can support unfortunately.
