### ISSUE TITLE
Add OMDB Support

### ISSUE THREAD

**Issue by nick-zrymiak** [sfu-db/DataConnectorConfigs#118]
Website Description
The OMDB API is a RESTful web service to obtain movie information.

Reason(s) to Support the Website
Developers can use this data to make movie database websites and apps.

Endpoints
The API supports 1 endpoint but two sets of parameters to access information:
1. By title or ID
2. By search

Technically there is only 1 endpoint: http://www.omdbapi.com/, but I will make 2 config files - 1 for each set of parameters

Questions
1. List Avengers movies from most to least popular
2. What is the order of the following movies from highest to lowest amount of money made: Titanic, Avatar, Skyfall
3. Is "The Notebook" a sad or happy movie?

**Comment by Lakshay-sethi** [comment]
looks good
