### ISSUE TITLE
Add TheSportsDB Support

### ISSUE THREAD

**Issue by nick-zrymiak** [sfu-db/DataConnectorConfigs#127]
Website Description
TheSportsDB API is a open, crowd-sourced database of sports artwork and metadata with a free API.

Reason(s) to Support the Website
Developers for sports-related apps can use this API to support their products.

Endpoints
https://www.thesportsdb.com/api/v1/json/1/eventspastleague.php
https://www.thesportsdb.com/api/v1/json/1/searchteams.php
https://www.thesportsdb.com/api/v1/json/1/all_sports.php
https://www.thesportsdb.com/api/v1/json/1/lookup_all_teams.php
https://www.thesportsdb.com/api/v1/json/1/lookupteam.php

Questions

1. What were scores of the last 10 NBA games?
2. What is the oldest sports team in Toronto?
3. What are all team sports supported by TheSportsDB?
4. Which NBA stadium has highest seating capacity?
5. What are social media links of the Vancouver Canucks?

**Comment by Wukkkinz-0725** [comment]
Hey Nick, the proposal looks good to me. 
Looking forward to your implementation!
