### ISSUE TITLE
For twitter dataset : can we make the query parameter optional.

### ISSUE THREAD

**Issue by peshotan** [sfu-db/DataConnectorConfigs#16]
Hi, at present we need a query parameter to get twitter data. But many projects on twitter just ask for random tweets (for example get 1000 random tweets from twitter). Can we change q parameter to optional.

**Comment by peiwangdb** [comment]
Thanks for the issue! @peterirani  Have you researched how this parameter work in the original Twitter API? If it was set to be optional, we should change as well.

**Comment by peshotan** [comment]
At present for our twitter API, we are using the`search API` and it looks like it q is a required parameter. I am looking for documentation for random tweet generation (not the search API) or we can assign `q` a default value and use the current search API.

**Comment by peiwangdb** [comment]
@peterirani Thanks! Sounds good! Once you figured out, we can definitely make the corresponding changes if needed.

**Comment by peshotan** [comment]
Hi Penny, passing q=False as the query parameter basically behaves as a Random fetch. It was not mentioned in the Twitter API docs, I found out by trial and error. I think we can close the issue now.
