### ISSUE TITLE
Avoid the image folder.

### ISSUE THREAD

**Issue by peiwangdb** [sfu-db/DataConnectorConfigs#21]
The image folder is superfluous and makes it look like a website name.
We should avoid putting it under the root folder and move it to other places appropriate.

**Comment by nick-zrymiak** [comment]
In the dataprep repo, the images for the README are kept under a folder in the root directory called "assets" . To mirror this repo and not a GitHub repo for a website, the images folder could simply be renamed to assets. 

Another solution is to transfer the information from the README file to the dataprep user guide. The README file on GitHub could then be replaced with a link to the same information in the user guide and the image folder could be removed altogether.

Please comment your input.

**Comment by nick-zrymiak** [comment]
In the dataprep repo, the images for the README are kept under a folder in the root directory called "assets" . To mirror this repo and not a GitHub repo for a website, the images folder could simply be renamed to assets.

Another solution is to transfer the information from the README file to the dataprep user guide. The README file on GitHub could then be replaced with a link to the same information in the user guide and the images folder could be removed altogether.

Please comment your input.

**Comment by jnwang** [comment]
Good job @nick-zrymiak ! 

At this moment, let's go with solution 1 since it is a quick fix. One minor comment: can we change it to ".assets" rather than "assets"?

Later, once the auto-config generator feature is implemented, we can change it to solution 2.

**Comment by nick-zrymiak** [comment]
Thanks for the input @jnwang, will do!
