### ISSUE TITLE
Add contribution table for readme

### ISSUE THREAD

**Issue by peiwangdb** [sfu-db/DataConnectorConfigs#33]
Design and add a table to show the contributors of each configuration file in the readme page.
Please refer to this presentation here https://github.com/all-contributors/all-contributors#contributors-

**Comment by dovahcrow** [comment]
Does this tool support showing the contributors for each config file?

**Comment by h-asmat** [comment]
@dovahcrow would you like that to be made specific in the table as well?

**Comment by h-asmat** [comment]
@dovahcrow ah I understand your question now! I will explore and see if that is possible :)
