### ISSUE TITLE
Etsy is capitalized 

### ISSUE THREAD

**Issue by jnwang** [sfu-db/DataConnectorConfigs#57]
"Etsy" is the only website whose folder name is capitalized. Is it a bug?

<img width="162" alt="Screen Shot 2020-12-27 at 8 13 52 PM" src="https://user-images.githubusercontent.com/1028970/103189163-3b218b80-4880-11eb-91dd-56030b1b31dd.png">

**Comment by dovahcrow** [comment]
Ya I think so. Thanks for the report.
