### ISSUE TITLE
Feature Proposal: Add Currents and CoinGecko apis

### ISSUE THREAD

**Issue by Wukkkinz-0725** [sfu-db/DataConnectorConfigs#62]
## Summary
Implement currents and coingecko API's configurationto DataConnectorConfigs

## Currents
* **Website:** 
   https://currentsapi.services/en

* **Description of the websites:**
   Currents api is an API for news data.

* **Why to support this websites:**
   This website can show us latest news, also can search news manually. I think some data scientists or students who want to do some research on news data will use this API

* **Endpoints:**
   * https://api.currentsapi.services/v1/search
   * https://api.currentsapi.services/v1/latest_news

* **Questions:**
   * How to get latest Chinese news?
   * How to get the political news about 'Trump'?
   * How to get the news about COVID-19 from 2020-12-25?

## CoinGecko
* **Website:** 
   https://www.coingecko.com

* **Description of the websites:**
   CoinGecko provides live pricing, trading volume, stocks, exchanges, historical data and other cryptocurrency data.

* **Why to support this websites:**
   User can get the live data and historical data of cryptocurrency. I think cryptocurrency investors or researchers will use this API.

* **Endpoints:**
   * https://api.coingecko.com/api/v3/coins/list
   * https://api.coingecko.com/api/v3/exchanges
   * https://api.coingecko.com/api/v3/search/trending
   * https://api.coingecko.com/api/v3/coins/markets
   * https://api.coingecko.com/api/v3/derivatives

* **Questions:**
   * What are the 10 cryptocurrencies with highest market cap and their current information?
   * What are the cryptocurrencies with highest increasing and decreasing percentage?
   * Which cryptocurrencies are trending in CoinGecko?
   * What are the 10 US exchanges with highest trade volume in the past 24 hours?
   * What are the 3 latest traded derivatives with perpetual contract?

**Comment by nick-zrymiak** [comment]
Looks good! I would just say add some more endpoints and questions. A requirement is there should be at least 5 endpoints per website and at least 1 question per endpoint being added. If one of the websites has fewer than 5 endpoints then can just make minimum 3 questions for the website and one config file per endpoint and mention the number of enpoints the API has. Good job!
