### ISSUE TITLE
Add Statcan API support

### ISSUE THREAD

**Issue by nick-zrymiak** [sfu-db/DataConnectorConfigs#81]
**Website Description**
Provides data of Canada's economy, society and environment.

**Reason(s) to Support the Website**
Developers will be able to identify relationships between types of Canadian demographic data.

**Endpoints**
https://www12.statcan.gc.ca/rest/census-recensement/CR2016geo.json
https://www12.statcan.gc.ca/rest/census-recensement/CPR2016.json
https://www150.statcan.gc.ca/n1/dai-quo/ssi/homepage/ind-econ.json
https://www150.statcan.gc.ca/n1/dai-quo/ssi/homepage/ind-hp.json
https://www150.statcan.gc.ca/n1/dai-quo/ssi/homepage/schedule-key_indicators-eng.json

**Questions**
1. What is the age-sex distribution in the South Surrey-White Rock federal riding?
2. Which city in Canada has the highest percentage of Tamil-speaking people?
3. What types of post-secondary programs are most popular for each sex?
4. What is the relationship between language spoken and marital status?
5. Which city has the highest percentage of divorced couples?

**Comment by Lakshay-sethi** [comment]
Looks good!  Look into the questions a little more. Other than that good job!
