### ISSUE TITLE
Feature Proposal: Add iTunes Search API

### ISSUE THREAD

**Issue by Wukkkinz-0725** [sfu-db/DataConnectorConfigs#82]
**Website Description**
Search for content within the iTunes Store and Apple Books Store.

**Reason(s) to Support the Website**
Developers will be able to search for a variety of content; including books, movies, podcasts, music, music videos, audiobooks, and TV shows.

**Endpoints**
https://itunes.apple.com/search?term=jack+johnson
https://itunes.apple.com/search?term=jack+johnson&entity=musicVideo
https://itunes.apple.com/search?term=jim+jones&country=ca
https://itunes.apple.com/lookup?id=909253&entity=album
https://itunes.apple.com/lookup?isbn=9780316069359

**Questions**
1. What is Jack Johnson's music videos?
2. What are all Jim Jones audio and video content? (only the results from the Canada iTunes Store)
3. Look up a book by its 13 digit ISBN.
4. Look up a Movie by AMG Video ID.
5. Look up an album or video by its UPC.

**Comment by Lakshay-sethi** [comment]
Looks good!  Look into making the questions a little more better. Other than that good job!
