### ISSUE TITLE
Add Hunter API support

### ISSUE THREAD

**Issue by nick-zrymiak** [sfu-db/DataConnectorConfigs#85]
**Website Description**
Finds and verifies professional email addresses.

**Reason(s) to Support the Website**
Businesses can use this API to gather contact and professional information about people to send targeted advertisements to.

**Endpoints**
account
domain-search
email-count
email-verifier
email-finder

**Questions**
1. Who are executives of Intercom and what are their emails?
2. What is Dustin Moskovitz's email?
3. Are the emails of Stripe executives valid?
4. How many available requests do I have left?
5. What are the counts of each level of seniority of employees?

**Comment by Lakshay-sethi** [comment]
Looks good!  Good job!
