### ISSUE TITLE
Add IPLegit Support

### ISSUE THREAD

**Issue by nick-zrymiak** [sfu-db/DataConnectorConfigs#95]
Website Description
IPLegit is a service that gives information on IP addresses.

Reason(s) to Support the Website
This can be used to detect fraudulent IP addresses.

Endpoints
- This API supports 2 endpoints
https://api.iplegit.com/full
https://api.iplegit.com/info

Questions
Given a list of IP addresses from people who have visited a my website...
1. How can I check if someone's IP address is bad, so I can block them from my website? (will just write a print statement saying they have been blocked)
2. What country are most people from, who have visited my website?
3. Make a map showing locations of people who have visited my website.

**Comment by Wukkkinz-0725** [comment]
The proposal looks good. It might be better to add the url of endpoint~
